[build]
  publish = "public"
  command = "gatsby build"
  
[build.environment]
  NODE_VERSION = "12"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
from = "http://adfreeyoutube.com/*"
to = "https://adfreeyt.com/:splat"
status = 301
force = true
[[redirects]]
from = "https://adfreeyoutube.com/*"
to = "https://adfreeyt.com/:splat"
status = 301
force = true